-- GENERATED by src/lib/safety/gate-sql.ts from src/lib/safety/__eval__/gate-corpus.ts. Don't edit by hand.
-- The database message gate must agree with the TypeScript one on every case:
-- the same rule (or none), and the same normalized views of the text.
--
--   Success looks like:  ERROR: ALL MESSAGE GATE TESTS PASSED (rolled back): N cases
--   Failure looks like:  ERROR: FAIL message gate: ...

create or replace function pg_temp.expect(p_text text, p_side text, p_rule text, p_views text)
returns void language plpgsql as $fn$
declare
  v_rule text;
  v_views jsonb;
begin
  select rule into v_rule from private.gate_check(p_text, p_side);
  if v_rule is distinct from p_rule then
    raise exception 'FAIL message gate: % (side %) gave rule %, TypeScript gave %', p_text, p_side, v_rule, p_rule;
  end if;
  v_views := private.gate_views(p_text);
  if v_views <> p_views::jsonb then
    raise exception 'FAIL message gate views for %: database % / TypeScript %', p_text, v_views, p_views;
  end if;
  if (private.message_violation(p_text, p_side) is null) <> (p_rule is null) then
    raise exception 'FAIL message_violation disagrees with gate_check for %', p_text;
  end if;
end $fn$;

do $test$
begin
  perform pg_temp.expect($t$add me on ѕnapchat$t$, null, 'app_name', $v${"base":"add me on snapchat","canon":"add me on snapchat","squash":"addmeonsnapchat","digits":"  "}$v$);
  perform pg_temp.expect($t$add me on snap​chat$t$, null, 'app_name', $v${"base":"add me on snapchat","canon":"add me on snapchat","squash":"addmeonsnapchat","digits":"  "}$v$);
  perform pg_temp.expect($t$s n a p c h a t$t$, null, 'app_name', $v${"base":"s n a p c h a t","canon":"snapchat","squash":"snapchat","digits":"  "}$v$);
  perform pg_temp.expect($t$s.n.a.p.c.h.a.t$t$, null, 'app_name', $v${"base":"s.n.a.p.c.h.a.t","canon":"snapchat","squash":"snapchat","digits":"  "}$v$);
  perform pg_temp.expect($t$sn@pchat me$t$, null, 'email_address', $v${"base":"sn@pchat me","canon":"snapchat me","squash":"snapchatme","digits":"  "}$v$);
  perform pg_temp.expect($t$$napchat$t$, null, 'app_name', $v${"base":"$napchat","canon":"snapchat","squash":"snapchat","digits":"  "}$v$);
  perform pg_temp.expect($t$sn ap ch at$t$, null, 'app_name_squashed', $v${"base":"sn ap ch at","canon":"sn ap ch at","squash":"snapchat","digits":"  "}$v$);
  perform pg_temp.expect($t$ＳＮＡＰＣＨＡＴ$t$, null, 'app_name', $v${"base":"snapchat","canon":"snapchat","squash":"snapchat","digits":"  "}$v$);
  perform pg_temp.expect($t$𝐬𝐧𝐚𝐩𝐜𝐡𝐚𝐭$t$, null, 'app_name', $v${"base":"snapchat","canon":"snapchat","squash":"snapchat","digits":"  "}$v$);
  perform pg_temp.expect($t$Ⓢⓝⓐⓟⓒⓗⓐⓣ$t$, null, 'app_name', $v${"base":"snapchat","canon":"snapchat","squash":"snapchat","digits":"  "}$v$);
  perform pg_temp.expect($t$s̷n̷a̷p̷c̷h̷a̷t̷$t$, null, 'app_name', $v${"base":"snapchat","canon":"snapchat","squash":"snapchat","digits":"  "}$v$);
  perform pg_temp.expect($t$my snap is leo_22$t$, null, 'offsite_ask', $v${"base":"my snap is leo_22","canon":"my snap is leo 22","squash":"mysnapisleo","digits":" 22 "}$v$);
  perform pg_temp.expect($t$my sc is leo22$t$, null, 'offsite_ask', $v${"base":"my sc is leo22","canon":"my sc is leo22","squash":"myscisleo","digits":" 22 "}$v$);
  perform pg_temp.expect($t$add me on insta$t$, null, 'app_name', $v${"base":"add me on insta","canon":"add me on instagram","squash":"addmeoninsta","digits":"  "}$v$);
  perform pg_temp.expect($t$my ig is leoplays$t$, null, 'app_name', $v${"base":"my ig is leoplays","canon":"my instagram is leoplays","squash":"myigisleoplays","digits":"  "}$v$);
  perform pg_temp.expect($t$ig: leoplays$t$, null, 'app_name', $v${"base":"ig: leoplays","canon":"instagram leoplays","squash":"igleoplays","digits":"  "}$v$);
  perform pg_temp.expect($t$my discord is leo$t$, null, 'app_name', $v${"base":"my discord is leo","canon":"my discord is leo","squash":"mydiscordisleo","digits":"  "}$v$);
  perform pg_temp.expect($t$whats4pp me$t$, null, 'app_name', $v${"base":"whats4pp me","canon":"whatsapp me","squash":"whatsappme","digits":" 4 "}$v$);
  perform pg_temp.expect($t$find me on tik tok$t$, null, 'app_name', $v${"base":"find me on tik tok","canon":"find me on tik tok","squash":"findmeontiktok","digits":"  "}$v$);
  perform pg_temp.expect($t$venm0 me 20$t$, null, 'app_name', $v${"base":"venm0 me 20","canon":"venmo me 20","squash":"venmome","digits":" 0 20 "}$v$);
  perform pg_temp.expect($t$c4sh app$t$, null, 'app_name', $v${"base":"c4sh app","canon":"cash app","squash":"cashapp","digits":" 4 "}$v$);
  perform pg_temp.expect($t$inst4gram$t$, null, 'app_name', $v${"base":"inst4gram","canon":"instagram","squash":"instagram","digits":" 4 "}$v$);
  perform pg_temp.expect($t$dm me$t$, null, 'offsite_ask', $v${"base":"dm me","canon":"dm me","squash":"dmme","digits":"  "}$v$);
  perform pg_temp.expect($t$text me$t$, null, 'offsite_ask', $v${"base":"text me","canon":"text me","squash":"textme","digits":"  "}$v$);
  perform pg_temp.expect($t$txt me later$t$, null, 'offsite_ask', $v${"base":"txt me later","canon":"text me later","squash":"txtmelater","digits":"  "}$v$);
  perform pg_temp.expect($t$hit me up$t$, null, 'offsite_ask', $v${"base":"hit me up","canon":"hit me up","squash":"hitmeup","digits":"  "}$v$);
  perform pg_temp.expect($t$u can facetime me$t$, null, 'app_name', $v${"base":"u can facetime me","canon":"you can facetime me","squash":"ucanfacetimeme","digits":"  "}$v$);
  perform pg_temp.expect($t$my gmail is leoplays2012$t$, null, 'email_provider', $v${"base":"my gmail is leoplays2012","canon":"my gmail is leoplays2oi2","squash":"mygmailisleoplaysoi","digits":" 1 0 1 2012 "}$v$);
  perform pg_temp.expect($t$leoplays2012 at gmail$t$, null, 'email_provider', $v${"base":"leoplays2012 at gmail","canon":"leoplays2oi2 at gmail","squash":"leoplaysoiatgmail","digits":" 1 0 1 2012 "}$v$);
  perform pg_temp.expect($t$leo at gmail dot com$t$, null, 'email_spelled', $v${"base":"leo at gmail dot com","canon":"leo at gmail dot com","squash":"leoatgmaildotcom","digits":"  "}$v$);
  perform pg_temp.expect($t$leo (at) gmail (dot) com$t$, null, 'email_spelled', $v${"base":"leo (at) gmail (dot) com","canon":"leo at gmail dot com","squash":"leoatgmaildotcom","digits":"  "}$v$);
  perform pg_temp.expect($t$leo＠gmail．com$t$, null, 'email_address', $v${"base":"leo@gmail.com","canon":"leoagmail com","squash":"leoagmailcom","digits":"  "}$v$);
  perform pg_temp.expect($t$leo@gmail$t$, null, 'email_address', $v${"base":"leo@gmail","canon":"leoagmail","squash":"leoagmail","digits":"  "}$v$);
  perform pg_temp.expect($t$email me$t$, null, 'offsite_ask', $v${"base":"email me","canon":"email me","squash":"emailme","digits":"  "}$v$);
  perform pg_temp.expect($t$5 5 5 8 6 7 5 3 0 9$t$, null, 'phone_single_digits', $v${"base":"5 5 5 8 6 7 5 3 0 9","canon":"5558675309","squash":"","digits":" 5-5-5-8-6-7-5-3-0-9 "}$v$);
  perform pg_temp.expect($t$9 1 9 5 5 5 1 2 3 4$t$, null, 'phone_single_digits', $v${"base":"9 1 9 5 5 5 1 2 3 4","canon":"9195551234","squash":"","digits":" 9-1-9-5-5-5-1-2-3-4 "}$v$);
  perform pg_temp.expect($t$919 five five five 1234$t$, null, 'phone_grouped', $v${"base":"919 five five five 1234","canon":"919 five five five 1234","squash":"fivefivefive","digits":" 919-5-5-5-1234 "}$v$);
  perform pg_temp.expect($t$nine one nine five five five one two three four$t$, null, 'phone_single_digits', $v${"base":"nine one nine five five five one two three four","canon":"nine one nine five five five one two three four","squash":"nineoneninefivefivefiveonetwothreefour","digits":" 9-1-9-5-5-5-1-2-3-4 "}$v$);
  perform pg_temp.expect($t$919-555-I234$t$, null, 'phone_grouped', $v${"base":"919-555-i234","canon":"9i9 ss i2ea","squash":"issiea","digits":" 919-555-1234 "}$v$);
  perform pg_temp.expect($t$９１９５５５１２３４$t$, null, 'phone_formatted', $v${"base":"9195551234","canon":"9195551234","squash":"","digits":" 9195551234 "}$v$);
  perform pg_temp.expect($t$919 555 12 34$t$, null, 'phone_grouped', $v${"base":"919 555 12 34","canon":"919 555 12 34","squash":"","digits":" 919-555-12-34 "}$v$);
  perform pg_temp.expect($t$919_555_1234$t$, null, 'phone_grouped', $v${"base":"919_555_1234","canon":"919 555 1234","squash":"","digits":" 919-555-1234 "}$v$);
  perform pg_temp.expect($t$919/555/1234$t$, null, 'phone_grouped', $v${"base":"919/555/1234","canon":"919 555 1234","squash":"","digits":" 919-555-1234 "}$v$);
  perform pg_temp.expect($t$call 867-5309$t$, null, 'phone_local', $v${"base":"call 867-5309","canon":"call 867 5309","squash":"call","digits":" 867-5309 "}$v$);
  perform pg_temp.expect($t$my number: 91 95 55 12 34$t$, null, 'phone_with_cue', $v${"base":"my number: 91 95 55 12 34","canon":"my number 91 95 55 12 34","squash":"mynumber","digits":" 91-95-55-12-34 "}$v$);
  perform pg_temp.expect($t$9195551234$t$, null, 'phone_formatted', $v${"base":"9195551234","canon":"9195551234","squash":"","digits":" 9195551234 "}$v$);
  perform pg_temp.expect($t$+1 (919) 555-1234$t$, null, 'phone_formatted', $v${"base":"+1 (919) 555-1234","canon":"1 919 555 1234","squash":"","digits":" 1-919-555-1234 "}$v$);
  perform pg_temp.expect($t$w w w . e v i l . c o m$t$, null, 'link_words', $v${"base":"w w w . e v i l . c o m","canon":"ww evil com","squash":"wwevilcom","digits":"  "}$v$);
  perform pg_temp.expect($t$evil dot com$t$, null, 'link_words', $v${"base":"evil dot com","canon":"evil dot com","squash":"evildotcom","digits":"  "}$v$);
  perform pg_temp.expect($t$evil[.]com$t$, null, 'link_defanged', $v${"base":"evil[.]com","canon":"evil com","squash":"evilcom","digits":"  "}$v$);
  perform pg_temp.expect($t$youtube.com/watch?v=x$t$, null, 'link_domain', $v${"base":"youtube.com/watch?v=x","canon":"youtube com watch v x","squash":"youtubecomwatchvx","digits":"  "}$v$);
  perform pg_temp.expect($t$bit.ly/abc$t$, null, 'link_domain', $v${"base":"bit.ly/abc","canon":"bit ly abc","squash":"bitlyabc","digits":"  "}$v$);
  perform pg_temp.expect($t$https://evil.test/x$t$, null, 'link_scheme', $v${"base":"https://evil.test/x","canon":"https evil test x","squash":"httpseviltestx","digits":"  "}$v$);
  perform pg_temp.expect($t$dm @leo_plays$t$, null, 'handle_at', $v${"base":"dm @leo_plays","canon":"dm aleo plays","squash":"dmaleoplays","digits":"  "}$v$);
  perform pg_temp.expect($t$my username is leo_plays$t$, null, 'handle_words', $v${"base":"my username is leo_plays","canon":"my username is leo plays","squash":"myusernameisleoplays","digits":"  "}$v$);
  perform pg_temp.expect($t$come to my place$t$, null, 'meet_visit', $v${"base":"come to my place","canon":"come to my place","squash":"cometomyplace","digits":"  "}$v$);
  perform pg_temp.expect($t$i can pick u up$t$, null, 'meet_visit', $v${"base":"i can pick u up","canon":"i can pick you up","squash":"icanpickuup","digits":"  "}$v$);
  perform pg_temp.expect($t$lets hang out irl$t$, null, 'meet_visit', $v${"base":"lets hang out irl","canon":"let's hang out irl","squash":"letshangoutirl","digits":"  "}$v$);
  perform pg_temp.expect($t$we should meet up at the park$t$, null, 'meet_up', $v${"base":"we should meet up at the park","canon":"we should meet up at the park","squash":"weshouldmeetupatthepark","digits":"  "}$v$);
  perform pg_temp.expect($t$c0me 0ver after school$t$, null, 'meet_visit', $v${"base":"c0me 0ver after school","canon":"come over after school","squash":"comeoverafterschool","digits":" 0 0 "}$v$);
  perform pg_temp.expect($t$f u c k$t$, null, 'bad_language', $v${"base":"f u c k","canon":"fuck","squash":"fuck","digits":"  "}$v$);
  perform pg_temp.expect($t$phuck$t$, null, 'bad_language', $v${"base":"phuck","canon":"phuck","squash":"phuck","digits":"  "}$v$);
  perform pg_temp.expect($t$sh1t$t$, null, 'bad_language', $v${"base":"sh1t","canon":"shit","squash":"shit","digits":" 1 "}$v$);
  perform pg_temp.expect($t$b1tch$t$, null, 'bad_language', $v${"base":"b1tch","canon":"bitch","squash":"bitch","digits":" 1 "}$v$);
  perform pg_temp.expect($t$ѕех$t$, null, 'bad_language', $v${"base":"sex","canon":"sex","squash":"sex","digits":"  "}$v$);
  perform pg_temp.expect($t$s3nd n00dz$t$, null, 'bad_language', $v${"base":"s3nd n00dz","canon":"send noodz","squash":"sendnoodz","digits":" 3 00 "}$v$);
  perform pg_temp.expect($t$don't tell your mom$t$, null, 'secret_tell', $v${"base":"don't tell your mom","canon":"don't tell your mom","squash":"donttellyourmom","digits":"  "}$v$);
  perform pg_temp.expect($t$dont tell ur parents ok$t$, null, 'secret_tell', $v${"base":"dont tell ur parents ok","canon":"don't tell your parents ok","squash":"donttellurparentsok","digits":"  "}$v$);
  perform pg_temp.expect($t$keep this between us$t$, null, 'secret_keep', $v${"base":"keep this between us","canon":"keep this between us","squash":"keepthisbetweenus","digits":"  "}$v$);
  perform pg_temp.expect($t$this is our little secret$t$, null, 'secret_keep', $v${"base":"this is our little secret","canon":"this is our little secret","squash":"thisisourlittlesecret","digits":"  "}$v$);
  perform pg_temp.expect($t$delete this chat$t$, null, 'secret_delete', $v${"base":"delete this chat","canon":"delete this chat","squash":"deletethischat","digits":"  "}$v$);
  perform pg_temp.expect($t$pls delete our msgs$t$, null, 'secret_delete', $v${"base":"pls delete our msgs","canon":"please delete our messages","squash":"plsdeleteourmsgs","digits":"  "}$v$);
  perform pg_temp.expect($t$no one needs to know$t$, null, 'secret_keep', $v${"base":"no one needs to know","canon":"no one needs to know","squash":"nooneneedstoknow","digits":" 1 "}$v$);
  perform pg_temp.expect($t$are you home alone$t$, null, 'probe_alone', $v${"base":"are you home alone","canon":"are you home alone","squash":"areyouhomealone","digits":"  "}$v$);
  perform pg_temp.expect($t$r u home alone rn$t$, null, 'probe_alone', $v${"base":"r u home alone rn","canon":"are you home alone right now","squash":"ruhomealonern","digits":"  "}$v$);
  perform pg_temp.expect($t$are your parents home?$t$, null, 'probe_parents', $v${"base":"are your parents home?","canon":"are your parents home","squash":"areyourparentshome","digits":"  "}$v$);
  perform pg_temp.expect($t$when do your parents go to bed$t$, null, 'probe_parents', $v${"base":"when do your parents go to bed","canon":"when do your parents go to bed","squash":"whendoyourparentsgotobed","digits":"  "}$v$);
  perform pg_temp.expect($t$is your door locked$t$, null, 'probe_room', $v${"base":"is your door locked","canon":"is your door locked","squash":"isyourdoorlocked","digits":"  "}$v$);
  perform pg_temp.expect($t$where do you live$t$, null, 'probe_where', $v${"base":"where do you live","canon":"where do you live","squash":"wheredoyoulive","digits":"  "}$v$);
  perform pg_temp.expect($t$send me a selfie$t$, null, 'photo_of_you', $v${"base":"send me a selfie","canon":"send me a selfie","squash":"sendmeaselfie","digits":"  "}$v$);
  perform pg_temp.expect($t$send me a pic of you$t$, null, 'photo_of_you', $v${"base":"send me a pic of you","canon":"send me a picture of you","squash":"sendmeapicofyou","digits":"  "}$v$);
  perform pg_temp.expect($t$what are you wearing$t$, null, 'photo_wearing', $v${"base":"what are you wearing","canon":"what are you wearing","squash":"whatareyouwearing","digits":"  "}$v$);
  perform pg_temp.expect($t$send a picture of your legs$t$, null, 'photo_body', $v${"base":"send a picture of your legs","canon":"send a picture of your legs","squash":"sendapictureofyourlegs","digits":"  "}$v$);
  perform pg_temp.expect($t$i love you$t$, 'tutor', 'affection_love', $v${"base":"i love you","canon":"i love you","squash":"iloveyou","digits":"  "}$v$);
  perform pg_temp.expect($t$you're so pretty$t$, 'tutor', 'affection_looks', $v${"base":"you're so pretty","canon":"you're so pretty","squash":"youresopretty","digits":"  "}$v$);
  perform pg_temp.expect($t$ur so cute$t$, 'tutor', 'affection_looks', $v${"base":"ur so cute","canon":"your so cute","squash":"ursocute","digits":"  "}$v$);
  perform pg_temp.expect($t$you look gorgeous$t$, 'tutor', 'affection_looks', $v${"base":"you look gorgeous","canon":"you look gorgeous","squash":"youlookgorgeous","digits":"  "}$v$);
  perform pg_temp.expect($t$you're mature for your age$t$, 'tutor', 'affection_looks', $v${"base":"you're mature for your age","canon":"you're mature for your age","squash":"yourematureforyourage","digits":"  "}$v$);
  perform pg_temp.expect($t$you're my favorite student$t$, 'tutor', 'affection_love', $v${"base":"you're my favorite student","canon":"you're my favorite student","squash":"youremyfavoritestudent","digits":"  "}$v$);
  perform pg_temp.expect($t$i'll buy you a gift card$t$, null, 'money_gifts', $v${"base":"i'll buy you a gift card","canon":"i'll buy you a gift card","squash":"illbuyyouagiftcard","digits":"  "}$v$);
  perform pg_temp.expect($t$want free robux$t$, null, 'money_gifts', $v${"base":"want free robux","canon":"want free robux","squash":"wantfreerobux","digits":"  "}$v$);
  perform pg_temp.expect($t$send me the code$t$, null, 'scam_codes', $v${"base":"send me the code","canon":"send me the code","squash":"sendmethecode","digits":"  "}$v$);
  perform pg_temp.expect($t$whats your password$t$, null, 'scam_codes', $v${"base":"whats your password","canon":"what's your password","squash":"whatsyourpassword","digits":"  "}$v$);
  perform pg_temp.expect($t$Leo practiced measures 12-24 for 20 minutes, 3 times this week.$t$, null, null, $v${"base":"leo practiced measures 12-24 for 20 minutes, 3 times this week.","canon":"leo practiced measures 12 24 for 20 minutes 3 times this week","squash":"leopracticedmeasuresforminutestimesthisweek","digits":" 12-24 20 3 "}$v$);
  perform pg_temp.expect($t$He is working on a sextet!$t$, null, null, $v${"base":"he is working on a sextet!","canon":"he is working on a sextet","squash":"heisworkingonasextet","digits":"  "}$v$);
  perform pg_temp.expect($t$Can we work on the Bb major scale and the 2nd movement?$t$, null, null, $v${"base":"can we work on the bb major scale and the 2nd movement?","canon":"can we work on the bb major scale and the 2nd movement","squash":"canweworkonthebbmajorscaleandthendmovement","digits":" 2 "}$v$);
  perform pg_temp.expect($t$Thanks! See you Thursday at 7.$t$, null, null, $v${"base":"thanks! see you thursday at 7.","canon":"thanks see you thursday at 7","squash":"thanksseeyouthursdayat","digits":" 7 "}$v$);
  perform pg_temp.expect($t$Page 45, exercises 1-10 please.$t$, null, null, $v${"base":"page 45, exercises 1-10 please.","canon":"page 45 exercises 1 10 please","squash":"pageexercisesplease","digits":" 45 1-10 "}$v$);
  perform pg_temp.expect($t$The concert is on 10/24 at 7:30.$t$, null, null, $v${"base":"the concert is on 10/24 at 7:30.","canon":"the concert is on 10 24 at 7 30","squash":"theconcertisonat","digits":" 10-24 7 30 "}$v$);
  perform pg_temp.expect($t$She has All-District auditions in January.$t$, null, null, $v${"base":"she has all-district auditions in january.","canon":"she has all district auditions in january","squash":"shehasalldistrictauditionsinjanuary","digits":"  "}$v$);
  perform pg_temp.expect($t$Let's focus on sixteenth notes at 88 bpm.$t$, null, null, $v${"base":"let's focus on sixteenth notes at 88 bpm.","canon":"let's focus on sixteenth notes at 88 bpm","squash":"letsfocusonsixteenthnotesatbpm","digits":" 88 "}$v$);
  perform pg_temp.expect($t$Metronome ladder: 72 76 80 84 88, then 92.$t$, null, null, $v${"base":"metronome ladder: 72 76 80 84 88, then 92.","canon":"metronome ladder 72 76 80 84 88 then 92","squash":"metronomeladderthen","digits":" 72-76-80-84-88 92 "}$v$);
  perform pg_temp.expect($t$Metronome: 60, 66, 72, 80, 88, 96, 104, 112, 120$t$, null, null, $v${"base":"metronome: 60, 66, 72, 80, 88, 96, 104, 112, 120","canon":"metronome 60 66 72 80 88 96 104 112 120","squash":"metronome","digits":" 60 66 72 80 88 96 104 112 120 "}$v$);
  perform pg_temp.expect($t$Count 1 2 3 4, 1 2 3 4 out loud.$t$, null, null, $v${"base":"count 1 2 3 4, 1 2 3 4 out loud.","canon":"count 1234 1234 out loud","squash":"countoutloud","digits":" 1-2-3-4 1-2-3-4 "}$v$);
  perform pg_temp.expect($t$count 1 2 3 4 5 6 7 8 9 10$t$, null, null, $v${"base":"count 1 2 3 4 5 6 7 8 9 10","canon":"count 123456789 10","squash":"count","digits":" 1-2-3-4-5-6-7-8-9-10 "}$v$);
  perform pg_temp.expect($t$Bars 112-128 and 132-140 slowly.$t$, null, null, $v${"base":"bars 112-128 and 132-140 slowly.","canon":"bars 112 128 and 132 140 slowly","squash":"barsandslowly","digits":" 112-128 132-140 "}$v$);
  perform pg_temp.expect($t$Bach lived 1685-1750.$t$, null, null, $v${"base":"bach lived 1685-1750.","canon":"bach lived 1685 1750","squash":"bachlived","digits":" 1685-1750 "}$v$);
  perform pg_temp.expect($t$Play the C major scale: c d e f g a b c$t$, null, null, $v${"base":"play the c major scale: c d e f g a b c","canon":"play the c major scale cdefgabc","squash":"playthecmajorscalecdefgabc","digits":"  "}$v$);
  perform pg_temp.expect($t$Long tones for 5 minutes a day, then the etude.$t$, null, null, $v${"base":"long tones for 5 minutes a day, then the etude.","canon":"long tones for 5 minutes a day then the etude","squash":"longtonesforminutesadaythentheetude","digits":" 5 "}$v$);
  perform pg_temp.expect($t$Send me a video of you playing the first page!$t$, null, null, $v${"base":"send me a video of you playing the first page!","canon":"send me a video of you playing the first page","squash":"sendmeavideoofyouplayingthefirstpage","digits":"  "}$v$);
  perform pg_temp.expect($t$Take a picture of your hand position so I can check it.$t$, null, null, $v${"base":"take a picture of your hand position so i can check it.","canon":"take a picture of your hand position so i can check it","squash":"takeapictureofyourhandpositionsoicancheckit","digits":"  "}$v$);
  perform pg_temp.expect($t$Send me a photo of your sheet music.$t$, null, null, $v${"base":"send me a photo of your sheet music.","canon":"send me a photo of your sheet music","squash":"sendmeaphotoofyoursheetmusic","digits":"  "}$v$);
  perform pg_temp.expect($t$Your tone is so beautiful in the slow section.$t$, 'tutor', null, $v${"base":"your tone is so beautiful in the slow section.","canon":"your tone is so beautiful in the slow section","squash":"yourtoneissobeautifulintheslowsection","digits":"  "}$v$);
  perform pg_temp.expect($t$You sounded amazing today!$t$, 'tutor', null, $v${"base":"you sounded amazing today!","canon":"you sounded amazing today","squash":"yousoundedamazingtoday","digits":"  "}$v$);
  perform pg_temp.expect($t$I'd love you to try it at 80 next week.$t$, 'tutor', null, $v${"base":"i'd love you to try it at 80 next week.","canon":"i'd love you to try it at 80 next week","squash":"idloveyoutotryitatnextweek","digits":" 80 "}$v$);
  perform pg_temp.expect($t$I love your vibrato!$t$, 'tutor', null, $v${"base":"i love your vibrato!","canon":"i love your vibrato","squash":"iloveyourvibrato","digits":"  "}$v$);
  perform pg_temp.expect($t$Omg thank you, I love you guys$t$, 'family', null, $v${"base":"omg thank you, i love you guys","canon":"omg thank you i love you guys","squash":"omgthankyouiloveyouguys","digits":"  "}$v$);
  perform pg_temp.expect($t$you're so cute when you get excited about scales lol$t$, 'family', null, $v${"base":"you're so cute when you get excited about scales lol","canon":"you're so cute when you get excited about scales lol","squash":"youresocutewhenyougetexcitedaboutscaleslol","digits":"  "}$v$);
  perform pg_temp.expect($t$The secret is air support.$t$, null, null, $v${"base":"the secret is air support.","canon":"the secret is air support","squash":"thesecretisairsupport","digits":"  "}$v$);
  perform pg_temp.expect($t$Keep it quiet in bar 12, then crescendo.$t$, null, null, $v${"base":"keep it quiet in bar 12, then crescendo.","canon":"keep it quiet in bar 12 then crescendo","squash":"keepitquietinbarthencrescendo","digits":" 12 "}$v$);
  perform pg_temp.expect($t$You killed that solo!$t$, null, null, $v${"base":"you killed that solo!","canon":"you killed that solo","squash":"youkilledthatsolo","digits":"  "}$v$);
  perform pg_temp.expect($t$Are your parents nearby for the lesson?$t$, null, null, $v${"base":"are your parents nearby for the lesson?","canon":"are your parents nearby for the lesson","squash":"areyourparentsnearbyforthelesson","digits":"  "}$v$);
  perform pg_temp.expect($t$Is a parent home for the lesson? They need to be nearby.$t$, null, null, $v${"base":"is a parent home for the lesson? they need to be nearby.","canon":"is a parent home for the lesson they need to be nearby","squash":"isaparenthomeforthelessontheyneedtobenearby","digits":"  "}$v$);
  perform pg_temp.expect($t$Meet me in the lesson link at 4.$t$, null, null, $v${"base":"meet me in the lesson link at 4.","canon":"meet me in the lesson link at 4","squash":"meetmeinthelessonlinkat","digits":" 4 "}$v$);
  perform pg_temp.expect($t$Let's meet up in the Google Meet at 5.$t$, null, null, $v${"base":"let's meet up in the google meet at 5.","canon":"let's meet up in the google meet at 5","squash":"letsmeetupinthegooglemeetat","digits":" 5 "}$v$);
  perform pg_temp.expect($t$What are you wearing for the concert? Concert black?$t$, null, null, $v${"base":"what are you wearing for the concert? concert black?","canon":"what are you wearing for the concert concert black","squash":"whatareyouwearingfortheconcertconcertblack","digits":"  "}$v$);
  perform pg_temp.expect($t$Play the Dm chord, then G7.$t$, null, null, $v${"base":"play the dm chord, then g7.","canon":"play the dm chord then gt","squash":"playthedmchordthengt","digits":" 7 "}$v$);
  perform pg_temp.expect($t$I hit a high C today!$t$, null, null, $v${"base":"i hit a high c today!","canon":"i hit a high c today","squash":"ihitahighctoday","digits":"  "}$v$);
  perform pg_temp.expect($t$My phone died during practice so I used the metronome app.$t$, null, null, $v${"base":"my phone died during practice so i used the metronome app.","canon":"my phone died during practice so i used the metronome app","squash":"myphonediedduringpracticesoiusedthemetronomeapp","digits":"  "}$v$);
  perform pg_temp.expect($t$Measure 9 has a dotted rhythm.$t$, null, null, $v${"base":"measure 9 has a dotted rhythm.","canon":"measure 9 has a dotted rhythm","squash":"measurehasadottedrhythm","digits":" 9 "}$v$);
  perform pg_temp.expect($t$Practice the passage in 3/4, then 6/8.$t$, null, null, $v${"base":"practice the passage in 3/4, then 6/8.","canon":"practice the passage in 3 4 then 6 8","squash":"practicethepassageinthen","digits":" 3-4 6-8 "}$v$);
  perform pg_temp.expect($t$From 2:15 to 2:45 I'll be free.$t$, null, null, $v${"base":"from 2:15 to 2:45 i'll be free.","canon":"from 2 15 to 2 45 i'll be free","squash":"fromtoillbefree","digits":" 2 15 2 45 "}$v$);
  perform pg_temp.expect($t$I'll text the scale fingering on the lesson card.$t$, null, null, $v${"base":"i'll text the scale fingering on the lesson card.","canon":"i'll text the scale fingering on the lesson card","squash":"illtextthescalefingeringonthelessoncard","digits":"  "}$v$);
  perform pg_temp.expect($t$Tempo 120, then 132, then 144.$t$, null, null, $v${"base":"tempo 120, then 132, then 144.","canon":"tempo 120 then 132 then 144","squash":"tempothenthen","digits":" 120 132 144 "}$v$);
  perform pg_temp.expect($t$Do pages 12, 13 and 14 tonight.$t$, null, null, $v${"base":"do pages 12, 13 and 14 tonight.","canon":"do pages 12 13 and 14 tonight","squash":"dopagesandtonight","digits":" 12 13 14 "}$v$);
  perform pg_temp.expect($t$What's your favorite piece to play?$t$, null, null, $v${"base":"what's your favorite piece to play?","canon":"what's your favorite piece to play","squash":"whatsyourfavoritepiecetoplay","digits":"  "}$v$);
  perform pg_temp.expect($t$I'm free on Thursday, does that work?$t$, null, null, $v${"base":"i'm free on thursday, does that work?","canon":"i'm free on thursday does that work","squash":"imfreeonthursdaydoesthatwork","digits":"  "}$v$);
  perform pg_temp.expect($t$We did scales, arpeggios, and the first etude.$t$, null, null, $v${"base":"we did scales, arpeggios, and the first etude.","canon":"we did scales arpeggios and the first etude","squash":"wedidscalesarpeggiosandthefirstetude","digits":"  "}$v$);
  perform pg_temp.expect($t$Remember to warm up first: lip slurs, then long tones.$t$, null, null, $v${"base":"remember to warm up first: lip slurs, then long tones.","canon":"remember to warm up first lip slurs then long tones","squash":"remembertowarmupfirstlipslursthenlongtones","digits":"  "}$v$);
  perform pg_temp.expect($t$Great job holding the bow today!$t$, null, null, $v${"base":"great job holding the bow today!","canon":"great job holding the bow today","squash":"greatjobholdingthebowtoday","digits":"  "}$v$);
  perform pg_temp.expect($t$Clean the reed after every practice.$t$, null, null, $v${"base":"clean the reed after every practice.","canon":"clean the reed after every practice","squash":"cleanthereedaftereverypractice","digits":"  "}$v$);
  perform pg_temp.expect($t$I'd like you to record yourself playing and listen back.$t$, null, null, $v${"base":"i'd like you to record yourself playing and listen back.","canon":"i'd like you to record yourself playing and listen back","squash":"idlikeyoutorecordyourselfplayingandlistenback","digits":"  "}$v$);
  perform pg_temp.expect($t$Who's your band director?$t$, null, null, $v${"base":"who's your band director?","canon":"who's your band director","squash":"whosyourbanddirector","digits":"  "}$v$);
  perform pg_temp.expect($t$Try the excerpt one more time at 60.$t$, null, null, $v${"base":"try the excerpt one more time at 60.","canon":"try the excerpt one more time at 60","squash":"trytheexcerptonemoretimeat","digits":" 1 60 "}$v$);
  perform pg_temp.expect($t$Bartók snap pizzicato in measure 14.$t$, null, null, $v${"base":"bartok snap pizzicato in measure 14.","canon":"bartok snap pizzicato in measure 14","squash":"bartoksnappizzicatoinmeasure","digits":" 14 "}$v$);
  perform pg_temp.expect($t$Rehearsal number 12 to 18 at quarter = 100.$t$, null, null, $v${"base":"rehearsal number 12 to 18 at quarter = 100.","canon":"rehearsal number 12 to 18 at quarter 100","squash":"rehearsalnumbertoatquarter","digits":" 12 18 100 "}$v$);
  perform pg_temp.expect($t$Measure number 12 14 16 18 need work.$t$, null, null, $v${"base":"measure number 12 14 16 18 need work.","canon":"measure number 12 14 16 18 need work","squash":"measurenumberneedwork","digits":" 12-14-16-18 "}$v$);
  raise exception 'ALL MESSAGE GATE TESTS PASSED (rolled back): 147 cases';
end
$test$;
